### ISSUE TITLE
No umlauts in text

### ISSUE THREAD

**Issue by smuenchowsl** [igoltz/babelium-zf2#5]
It seems that in text that is coming from the Babelium backend, umlauts are not taken over.
Example: https://lernen.goethe.de/moodle/mod/assign/view.php?id=45988409

The Role "GesprächspartnerIn" is displayed as "GesprchspartnerIn". The text "Bitte wählen Sie aus und sprechen Sie." is displayed as "Bitte whlen Sie aus und sprechen Sie."

This needs to be corrected. I checked the Babelium backend and there the text seems to be correct, so I assume there is an issue with taking the text from Babelium and displaying it on Moodle.

**Comment by igoltz** [comment]
I found in Service SubTitles.php that this is intentionally

        //Sanitize string to strip non ASCII chars (non printable) to avoid json decode errors
        $cleanSerialized = preg_replace('/[\x00-\x1F\x80-\xFF]/', "", $serialized);
        $subtitles = \Zend\Json\Json::decode($cleanSerialized, true);
